"use strict";
// let users : string[] = ["ali", "ahmed", "maxamed"];
// let numbers : number[] = [1,2,3,4,5];
// console.log(users);
// console.log(numbers);
let names = ["Alice", "Bob", "Charlie", "faraah", "maxamed"];
let grades = [85, 92, 78, 90, 88];
let statusList = [true, false, true, true, false];
names.push("Xaliimo");
grades.push(95);
statusList.push(false);
